version: "3.12"
services:
  app:
    image: ghcr.io/younghyen7956/gtp-fastapi-for-aws-deploy-test:latest
    container_name: docker-fastapi-deploy-server
    ports:
      - 8000:8000
    networks:
      - app

networks:
  app:
    driver: bridge